project:
  title: "Advanced Panel Data Analysis"
  type: website
  output-dir: docs
  
website:
  title: "Advanced Panel Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - 01_Intro.qmd
      - 02_Estimators1.qmd
      - 03_Estimators2.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ruettenauer/Advanced_Panel/
  site-url: "https://ruettenauer.github.io/Advanced_Panel/"    
  

      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true   

execute:
  echo: true
  cache: true


bibliography: DID.bib   
